version: '3.9'
services:
  users_backend:
    build: .
    restart: always
    ports:
      - 8001:8000
    depends_on:
      - users_db
    volumes:
      - .:/app
    

  users_db:
    image: postgres:13
    volumes:
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always
    environment:
        - POSTGRES_HOST=users_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=users_db
    ports:
        - 5436:5436
