version: '3.9'
services:
  users_backend:
    build: .
    restart: always
    ports:
      - 8001:8000
    depends_on:
      users_db:
        condition: service_healthy
    volumes:
      - .:/app
    networks:
      - users_network

    

  users_db:
    image: postgres:13-alpine
    volumes:
        - data:/var/lib/postgresql/data
        - ./sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    restart: always
    environment:
        - POSTGRES_HOST=users_db
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=users_db
    ports:
        - 5436:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - users_network

volumes:
  data:

networks:
  users_network:

    
